TestTask/TestTask/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TestTask.Models;
using TestTask.Services.Interfaces;

namespace TestTask.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;

        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService; 
        }

        public IActionResult Back()
        {
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index(string title, string company, string type, int page = 1)
        {
            int userId = Convert.ToInt32(HttpContext.User.Claims.ToList()[1].Value);
            int role = Convert.ToInt32(HttpContext.User.Claims.ToList()[2].Value);
            ViewData["Role"] = role;
            
            List<ProjectModel> list = null;
            int projectsCount = 0;
            int projectsPerPage = 3;
            int skip = (page - 1) * projectsPerPage;
            

            if (role == (int)UserRoles.Admin)
            {
                projectsCount = await _projectService.GetProjectsCount(0, title, company, type);
                list = await _projectService.GetAllProjects(skip, projectsPerPage, title, company, type);
            }
            else
            {
                projectsCount = await _projectService.GetProjectsCount(userId, title, company, type);
                list = await _projectService.GetProjectsByUser(userId, skip, projectsPerPage, title, company, type);
            }

            PaginationModel pagination = new PaginationModel(projectsCount, page, projectsPerPage);
            FiltersModel filters = new FiltersModel()
            {
                Title = title,
                Company = company,
                Type = type
            };
            PageModel pageModel = new PageModel()
            {
                Projects = list,
                Pagination = pagination,
                Filters = filters
            };

            return View(pageModel);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProject(CreateProjectModel model)
        {
            int userId = Convert.ToInt32(HttpContext.User.Claims.ToList()[1].Value);
            List<string> skills = new List<string>();
            skills = model.Skills.Split(',').ToList();

            await _projectService.CreateProject(model.Project, userId, skills);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteProject(int id)
        {
            var result = await _projectService.Delete(id);

            if (result == null)
                return null;

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            HttpContext.Session.SetInt32("curProjectId", id);
            if (id == 0)
                id = (int)HttpContext.Session.GetInt32("curProjectId");

            var currentProject = await _projectService.Get(id);

            return View(currentProject);
        }

        [HttpPost]
        public async Task<IActionResult> EditProject(ProjectModel model)
        {
            var result = await _projectService.Edit(model);

            if (result == null)
                return null;

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id)
        {
            ProjectModel model = await _projectService.Get(id);
            if (!HttpContext.Session.Keys.Contains("curProjectId"))
                HttpContext.Session.SetInt32("curProjectId", id);

            return View(model);
        }
        
        

        public async Task<IActionResult> DeleteSkill(int id)
        {            
            var result = await _projectService.DeleteSkillProject(id);
            int projectId = (int)HttpContext.Session.GetInt32("curProjectId");
            return RedirectToAction("Edit", new { id = projectId });
        }

        public async Task<IActionResult> AddSkill(string skillName)
        {
            int projectId = (int)HttpContext.Session.GetInt32("curProjectId");


            var result = await _projectService.AddSkillProject(projectId, new SkillModel() { Skill = skillName});

            return RedirectToAction("Edit", new { id = projectId });
        }

    }
}

TestTask/TestTask/Views/Project/Create.cshtml
@model CreateProjectModel

@{
    ViewData["Title"] = "Create Project";
}

<h1>Create Project</h1>
<a asp-action="Back" class="btn btn-primary">Back</a>
@using (Html.BeginForm("AddProject", "Project", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.Project.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Title)
            @Html.ValidationMessageFor(model => model.Project.Title)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Description)
            @Html.ValidationMessageFor(model => model.Project.Description)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.Organization, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Organization)
            @Html.ValidationMessageFor(model => model.Project.Organization)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.Start, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Start)
            @Html.ValidationMessageFor(model => model.Project.Start)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.End, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.End)
            @Html.ValidationMessageFor(model => model.Project.End)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.Roles, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Roles)
            @Html.ValidationMessageFor(model => model.Project.Roles)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Skills, "Skills (write through ',')", new { @class = "control-label col-md-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Skills)
            @Html.ValidationMessageFor(model => model.Skills)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.Link, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Link)
            @Html.ValidationMessageFor(model => model.Project.Link)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Project.Type.Name, "Type", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.Type.Name)
            @Html.ValidationMessageFor(model => model.Project.Type.Name)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add" class="btn btn-primary" />
        </div>
    </div>

}


<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(document).on("click", "#btnDeleteSkill", function () {
        var row = $(this).closest("tr");
        var id = row.find("td:nth-child(1)").text();
    });

    $(document).on("click", "#btnAddSkill", function () {

        var skillName = $("#skillName").val();


        @*$.ajax({
            async: true,
            type: "POST",
            url: @Url.Action("AddSkill"),
            data: { skillName : skillName },
            dataType: 'text'
        });*@
    });

</script>

TestTask/TestTask/Views/Project/Details.cshtml
@model ProjectModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<a asp-action="Back" class="btn btn-primary">Back</a>
<div class="form-inline">
    <div class="col-md-5">
        @using (Html.BeginForm())
        {
            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Organization, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Organization)
                    @Html.ValidationMessageFor(model => model.Organization)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Start, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Start)
                    @Html.ValidationMessageFor(model => model.Start)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.End, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.End)
                    @Html.ValidationMessageFor(model => model.End)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Roles, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Roles)
                    @Html.ValidationMessageFor(model => model.Roles)
                </div>
            </div>

            <div>
                <div class="form-group editDiv">
                    @Html.LabelFor(model => model.SkillProject, "Skills", new { @class = "control-label col-md-2" })
                    <div class="col-md-5 overflowTable">
                        <table class="table table-striped table-bordered">
                            @foreach (SkillProjectModel item in @Model.SkillProject)
                            {
                                <tr>
                                    <td style="text-align:center">@item.Skill.Skill</td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Link)
                    @Html.ValidationMessageFor(model => model.Link)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Type.Name, "Type", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type.Name)
                    @Html.ValidationMessageFor(model => model.Type.Name)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Created, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Created)
                    @Html.ValidationMessageFor(model => model.Created)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Updated, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Updated)
                    @Html.ValidationMessageFor(model => model.Updated)
                </div>
            </div>
        }

    </div>
</div>

TestTask/TestTask/Views/Project/Edit.cshtml
@model ProjectModel

@{
    ViewData["Title"] = "Edit Project";
}

<h1>Edit Project</h1>
<a asp-action="Back" class="btn btn-primary">Back</a>

<div class="form-inline">
    <div class="col-md-6">
        @using (Html.BeginForm("EditProject", "Project", FormMethod.Post))
        {
            <div class="form-group editDiv">
                @Html.HiddenFor(model => model.Id)
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Organization, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Organization)
                    @Html.ValidationMessageFor(model => model.Organization)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Start, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Start, new { @value = Model.Start })
                    @Html.ValidationMessageFor(model => model.Start)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.End, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.End)
                    @Html.ValidationMessageFor(model => model.End)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Roles, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Roles)
                    @Html.ValidationMessageFor(model => model.Roles)
                </div>
            </div>

            <div>
                <div class="form-group editDiv">
                    @Html.LabelFor(model => model.SkillProject, "Skills", new { @class = "control-label col-md-2" })
                    <div class="col-md-5 overflowTable">
                        <table class="table table-striped table-bordered">
                            @foreach (SkillProjectModel item in @Model.SkillProject)
                            {
                                <tr>
                                    <td style="text-align:center">@item.Skill.Skill</td>
                                    <td><a id="btnDeleteSkill" asp-action="DeleteSkill" asp-route-id="@item.Id" class="btn btn-dark btn-sm">Delete</a></td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>         
            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Link)
                    @Html.ValidationMessageFor(model => model.Link)
                </div>
            </div>

            <div class="form-group editDiv">
                @Html.LabelFor(model => model.Type.Name, "Type", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type.Name)
                    @Html.ValidationMessageFor(model => model.Type.Name)
                </div>
            </div>

            <div class="form-group editDiv">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>

        }
    </div>
    <div>

        @using (Html.BeginForm("AddSkill", "Project", FormMethod.Post))
        {
            <div class="form-inline">
                <input name="skillName" class="form-control filterInput" />
                <input type="submit" name="btnAddSkill" value="Add" class="btn btn-primary" />
            </div>
        }

    </div>
</div>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(document).on("click", "#btnDeleteSkill", function () {
        var row = $(this).closest("tr");
        var id = row.find("td:nth-child(1)").text();
    });

</script>

TestTask/TestTask/Views/Project/Index.cshtml
@model PageModel

@{
    ViewData["Title"] = "Projects";
}

<h1>Projects</h1>

<a asp-action="Create" style="margin: 10px" class="btn btn-primary">Add Project</a>

<form method="get">
    <div class="form-inline">
        <label>Title:</label>
        <input name="Title" value="@Model.Filters.Title" class="form-control filterInput" />

        <label>Company: </label>
        <input name="Company" value="@Model.Filters.Company" class="form-control filterInput" />

        <label>Type: </label>
        <input name="Type" asp-items="Model.Filters.Type" class="form-control filterInput" />

        <input type="submit" value="Filter" class="btn btn-outline-dark filterInput" />
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Organization</th>
            <th>Type</th>
            <th>UserId</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (ProjectModel p in Model.Projects)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Title</td>
                <td>@p.Organization</td>
                <td>@p.Type.Name</td>
                <td>@p.User.Id</td>
                <td><a asp-action="Details" asp-route-id="@p.Id" class="btn btn-dark">Details</a></td>
                <td><a asp-action="Edit" asp-route-id="@p.Id" class="btn btn-warning">Edit</a></td>
                @if (Convert.ToInt32(ViewData["Role"].ToString()) == 2)
                {
                    <td><input type="button" id="btnDelete" class="btn btn-danger" value="Delete"></td>
                }
            </tr>
        }
    </tbody>
</table>
@if (Model.Pagination.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.Pagination.Page - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Previous
    </a>
}
@if (Model.Pagination.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.Pagination.Page + 1)"
       class="btn btn-outline-dark">
        Next
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(document).on("click", "#btnDelete", function () {
        var row = $(this).closest("tr");
        var id = row.find("td:nth-child(1)").text();
        $.ajax({
            url: '/Project/DeleteProject',
            data: { id: id }
        });
        $(this).closest("tr").remove();
    });
</script>